export const SKILLSET = [
  'React.js',
  'Redux',
  'Backbone.js',
  'Jest / Enzyme',
  'Node.js',
  'jQuery / jQuery UI / jQuery Mobile',
  'LESS / SASS / PostCSS',
  'styled-components',
  'Storybook',
  'Gulp / Grunt',
  'Webpack',
  'Optimizely',
  'Segment / Amplitude',
  'Adobe Experience Manager',
  'Squarespace',
  'Git / Subversion',
  'Jira / Team Foundation Server',
  'Adobe Photoshop / Illustrator / InDesign',
  'Zeplin / Figma / Sketch',
];
